// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-my-orders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.54.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool({
  name: "list_my_orders",
  title: "List my orders",
  description: "List orders placed by the signed-in Homemade customer, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max orders to return (default 10)."),
    status: z.string().optional().describe("Optional order status filter, e.g. 'succeeded'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb(ctx).from("orders").select("id, created_at, status, amount, currency, delivery_fee_cents, delivery_status, pickup_business_name, dropoff_address").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-menu-items.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.54.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_menu_items_default = defineTool2({
  name: "list_my_menu_items",
  title: "List my menu items",
  description: "List menu items owned by the signed-in chef.",
  inputSchema: {
    only_available: z2.boolean().optional().describe("If true, only return items marked available.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_available }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = sb2(ctx).from("menu_items").select("id, name, description, price, available, portions_available, prep_time_minutes, tags, image_url, created_at").eq("chef_user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (only_available) q = q.eq("available", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-menu-item.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.54.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_menu_item_default = defineTool3({
  name: "create_menu_item",
  title: "Create menu item",
  description: "Add a new menu item for the signed-in chef.",
  inputSchema: {
    name: z3.string().min(1).describe("Dish name."),
    price: z3.number().positive().describe("Price in dollars, e.g. 12.5."),
    description: z3.string().optional(),
    portions_available: z3.number().int().min(0).optional(),
    prep_time_minutes: z3.number().int().min(0).optional(),
    tags: z3.array(z3.string()).optional().describe("Tags like 'vegan', 'spicy'."),
    available: z3.boolean().optional().describe("Whether the item is currently available (default true).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb3(ctx).from("menu_items").insert({
      chef_user_id: ctx.getUserId(),
      name: input.name,
      description: input.description ?? null,
      price: input.price,
      portions_available: input.portions_available ?? null,
      prep_time_minutes: input.prep_time_minutes ?? null,
      tags: input.tags ?? null,
      available: input.available ?? true
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created menu item: ${data?.name} (${data?.id})` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/tools/get-my-chef-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.54.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_chef_profile_default = defineTool4({
  name: "get_my_chef_profile",
  title: "Get my chef profile",
  description: "Return the signed-in chef's profile: display name, online status, pickup area, Stripe onboarding status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb4(ctx).from("chef_profiles").select("display_name, pickup_business_name, pickup_address, city, zip, is_online, onboarding_complete, lat, lng").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No chef profile found." }], structuredContent: { profile: null } };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/search-nearby-dishes.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.54.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function sb5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function distanceMi(lat1, lng1, lat2, lng2) {
  const R = 3958.8;
  const toRad = (d) => d * Math.PI / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.asin(Math.sqrt(a));
}
var search_nearby_dishes_default = defineTool5({
  name: "search_nearby_dishes",
  title: "Search nearby dishes",
  description: "Find available menu items from online chefs near the given coordinates.",
  inputSchema: {
    lat: z4.number().describe("Latitude of the search origin."),
    lng: z4.number().describe("Longitude of the search origin."),
    radius_miles: z4.number().positive().optional().describe("Search radius in miles (default 15)."),
    query: z4.string().optional().describe("Optional text to match in dish name or description."),
    limit: z4.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lat, lng, radius_miles, query, limit }, ctx) => {
    const radius = radius_miles ?? 15;
    const cap = limit ?? 20;
    let q = sb5(ctx).from("menu_items").select("id, name, description, price, image_url, tags, chef_user_id, lat, lng").eq("available", true).not("lat", "is", null).not("lng", "is", null);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q.limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((r) => ({ ...r, distance_miles: distanceMi(lat, lng, r.lat, r.lng) })).filter((r) => r.distance_miles <= radius).sort((a, b) => a.distance_miles - b.distance_miles).slice(0, cap);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { dishes: results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uyoemkwlccljqyigmcch";
var mcp_default = defineMcp({
  name: "homemade-mcp",
  title: "Homemade",
  version: "0.1.0",
  instructions: "Tools for Homemade \u2014 a marketplace connecting customers with local home chefs. Customers can list their orders and search for nearby dishes. Chefs can view/update their profile and manage their menu items.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_orders_default,
    search_nearby_dishes_default,
    get_my_chef_profile_default,
    list_my_menu_items_default,
    create_menu_item_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
