// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyoemkwlccljqyigmcch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5b2Vta3dsY2NsanF5aWdtY2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzIyNDMsImV4cCI6MjA3MDUwODI0M30.wngJsOgYO73ZfJfY7tIqIf8KDePuBdCdegTOQmqR6cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});